# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  flutter_root = File.expand_path('..', File.expand_path('..', __dir__))


  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
