# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 14 Pro",       # 예: 6.1인치 Super Retina XDR
  "iPhone 14 Pro Max",   # 예: 6.7인치 Super Retina XDR
  "iPhone SE (3rd generation)", # 예: 4.7인치 Retina HD (iPhone 8 사이즈 호환)
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (11-inch) (4th generation)"
])
#   "Apple Watch Series 6 - 44mm"
# ])

languages([
  "en-US",
  "ko-KR"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
