name: iOS Release CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Fastlane 호환 버전

      - name: Install Bundler
        run: gem install bundler

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies (Flutter)
        run: |
          flutter pub get
        working-directory: .

      - name: Install iOS dependencies (CocoaPods)
        run: |
          cd ios
          pod install

      - name: Run Fastlane release
        run: |
          cd ios
          fastlane release
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          # 필요하다면 Apple ID 앱 특정 암호 등 추가
          # FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
